print("Welcome to Novaminds AI Solutions!")
print("I can help you with a variety of tasks including:")
print("- Answering questions")
print("- Providing recommendations")
print("- Assisting with coding problems")
print("- Generating creative content")
print("How can I assist you today?")
print("Whats your name?")
user_name = input()
print(f"Nice to meet you, {user_name}! Let's get started.")